Remove fail on warning from build
privacycg/storage-access pull request #136
Opened 2022-11-08 13:54 UTC by bvandersloot-mozilla

A large change to HTML landed and I am more willing to have broken links than a non-updating spec for now.

- [ ] At least two implementers are interested (and none opposed):
   * Mozilla
   * 
- [x] [Tests](https://github.com/web-platform-tests/wpt) are written and can be reviewed and commented upon at:
   * N/A
- [x] [Implementation bugs](https://github.com/whatwg/meta/blob/main/MAINTAINERS.md#handling-pull-requests) are filed:
   * N/A

2022-11-09 09:52 UTC, johannhof commented
Yeah, sorry, I told @domenic that we'd file an issue to investigate and told @bvandersloot-mozilla that we should consider ignoring the error in the meantime, to avoid breaking the build. I'll do the former part now.

2022-11-10 12:32 UTC, johannhof requested changes
I think I prefer Anne's suggestion on how to fix this in https://github.com/privacycg/storage-access/issues/137#issuecomment-1308781153

Would you mind making that change instead? :)

2022-11-14 15:46 UTC, annevk approved these changes

2022-11-16 12:55 UTC, johannhof approved these changes

2022-11-16 12:55 UTC, johannhof commented on storage-access.bs
> +ISSUE: Add links to current entry and session history to reflect the [navigation and session history rewrite](https://github.com/whatwg/html/pull/6315).
```suggestion
ISSUE(privacycg/storage-access#137): Add links to current entry and session history to reflect the [navigation and session history rewrite](https://github.com/whatwg/html/pull/6315).
```

2022-11-16 12:56 UTC, merged